# Generated by Django 4.2.4 on 2023-08-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveBigIntegerField(default=10000)),
                ('reputation', models.IntegerField(default=0)),
                ('products', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=1000)),
                ('production', models.IntegerField(default=1)),
                ('resource', models.IntegerField(default=10000)),
                ('tax', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
